### ISSUE TITLE
rp-adapter: support for "mixed scenario"

### ISSUE THREAD

**Issue by llorllale** [trustbloc/edge-adapter#232]
Need to support mixed scenarios where the RP requests both local[1] **and** remote data from the user.

Breakdown:

- [x] map OIDC scopes to presentation-exchange input descriptors #234
- [x] parse `presentation_submission` to select the appropriate authz cred to use for each credential request #247 
  - [x] Investigate the golang JSONPath library recommended by the presentation-exchange spec [here](https://identity.foundation/presentation-exchange/#jsonpath)
  - [x] ensure the presentation-definitions criteria has been met #247
    - [x] definition of "met": figure out level of support for criteria language
        * validation will be done at the coarse-grained "scope" level
  - [X] ~~tweak spec such that a submission's descriptor_mappings may contain "promise"-like credentials (authz)~~ not required
- [x] iterate through all authz credentials and perform the didcomm flow #247
- ~~validate remote credentials against presentation-definitions criteria #108~~ removed from scope
- [x] consolidate all VC credential subjects and map them to the id_token #161

[1] "local" == user is the holder of the credential. "remote" == credentials are at remote issuer

**Comment by llorllale** [comment]
removed #108 from this task's scope - support for "local + remote" credentials has been enabled, #108 is it's own separate issue
