### ISSUE TITLE
Proofs

### ISSUE THREAD

**Issue by llorllale** [trustbloc/edge-adapter#314]
- [ ] Issuer Adapter using a public DID when signing credentials and presentations in private contexts #230
- [ ] Wallet is using a public DID when signing presentations in private contexts trustbloc/edge-agent#322
- [ ] RP Adapter unable to verify proofs in credentials embedded in wallet's presentation submission #300 
  - RP Adapter needs to discover/be configured with the set trusted public issuers in order to verify proofs on local credentials
  - Wallet is passing the AuthZ credential issued to itself by the issuer
