### ISSUE TITLE
[Issuer Adapter] Support for Blinded Routing

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/edge-adapter#339]
Requirement: RP should communicate with Issuer through Router, rather than calling directly and vice versa.

The Issuer Adapter needs to register with user provided router and this router should be used by the RP to communicate with the Issuer Adapter.

The issuer-adapter DIDComm API should perform following tasks.
- [x] Provide a new PeerDID to the wallet #340 
- [x] Create manual connection with Router (using router's peerDID provided by the wallet) #341 
- [x] Register with the Router #342 
- [x] Use routers endpoint while creating the peerDID for AuthZ credential #343 
- [ ] Enforce blinded routing (throw error if router not registered)

Related https://github.com/trustbloc/hub-router/issues/23
