### ISSUE TITLE
RP Adapter: BDD Tests

### ISSUE THREAD

**Issue by llorllale** [trustbloc/edge-adapter#66]
- [x] Setup Hydra, RP Adapter, ~~MySQL~~, trustbloc-did-method #74
- Scenarios:
    - [x] Register RP tenant at both hydra and RP adapter #74
    - [x] did-exchange with wallet #132
    - [x] return data to the rp #147
